//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mInvoice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costs
    {
        public int Id { get; set; }
        public int clients_id { get; set; }
        public string description { get; set; }
        public Nullable<int> type_of_costs_id { get; set; }
        public Nullable<int> articles_id { get; set; }
        public Nullable<int> customers_id { get; set; }
        public System.DateTime booking_date { get; set; }
        public decimal value { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Type_of_costs Type_of_costs { get; set; }
        public virtual Articles Articles { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
