//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mInvoice.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mInvoice.App_GlobalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account no. ähnelt.
        /// </summary>
        public static string account_number {
            get {
                return ResourceManager.GetString("account_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active ähnelt.
        /// </summary>
        public static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All ähnelt.
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unexpected error has occurred. Please contact the system administrator. ähnelt.
        /// </summary>
        public static string an_unexpected_error {
            get {
                return ResourceManager.GetString("an_unexpected_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die mInvoices ähnelt.
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Archive ähnelt.
        /// </summary>
        public static string archive {
            get {
                return ResourceManager.GetString("archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Archive type ähnelt.
        /// </summary>
        public static string archive_type {
            get {
                return ResourceManager.GetString("archive_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure ? ähnelt.
        /// </summary>
        public static string are_you_sure {
            get {
                return ResourceManager.GetString("are_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you wish to change paying for this invoice? ähnelt.
        /// </summary>
        public static string are_you_sure_change_paying {
            get {
                return ResourceManager.GetString("are_you_sure_change_paying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to delete this? ähnelt.
        /// </summary>
        public static string are_you_sure_delete {
            get {
                return ResourceManager.GetString("are_you_sure_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Article ähnelt.
        /// </summary>
        public static string article {
            get {
                return ResourceManager.GetString("article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Article-No. ähnelt.
        /// </summary>
        public static string article_id {
            get {
                return ResourceManager.GetString("article_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Article-no. ähnelt.
        /// </summary>
        public static string article_no {
            get {
                return ResourceManager.GetString("article_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attention! All transactions and entries will be deleted! ähnelt.
        /// </summary>
        public static string attention_delete {
            get {
                return ResourceManager.GetString("attention_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back to List ähnelt.
        /// </summary>
        public static string back_to_list {
            get {
                return ResourceManager.GetString("back_to_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bank name ähnelt.
        /// </summary>
        public static string bank_name {
            get {
                return ResourceManager.GetString("bank_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Basic claims data ähnelt.
        /// </summary>
        public static string basic_claims_data {
            get {
                return ResourceManager.GetString("basic_claims_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BIC ähnelt.
        /// </summary>
        public static string bic {
            get {
                return ResourceManager.GetString("bic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BIC ähnelt.
        /// </summary>
        public static string bic_report {
            get {
                return ResourceManager.GetString("bic_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can*t open file. ähnelt.
        /// </summary>
        public static string cant_open_file {
            get {
                return ResourceManager.GetString("cant_open_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cash discount ähnelt.
        /// </summary>
        public static string cash_discount {
            get {
                return ResourceManager.GetString("cash_discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose file ähnelt.
        /// </summary>
        public static string choose_file {
            get {
                return ResourceManager.GetString("choose_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die City ähnelt.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Client ähnelt.
        /// </summary>
        public static string client {
            get {
                return ResourceManager.GetString("client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clients ähnelt.
        /// </summary>
        public static string clients {
            get {
                return ResourceManager.GetString("clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Code ähnelt.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you wish to copy this invoice? ähnelt.
        /// </summary>
        public static string confirm_copy_invoice {
            get {
                return ResourceManager.GetString("confirm_copy_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm password ähnelt.
        /// </summary>
        public static string confirm_password {
            get {
                return ResourceManager.GetString("confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy invoice ähnelt.
        /// </summary>
        public static string copy_invoice {
            get {
                return ResourceManager.GetString("copy_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Countries ähnelt.
        /// </summary>
        public static string countries {
            get {
                return ResourceManager.GetString("countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Countries ähnelt.
        /// </summary>
        public static string countriesid {
            get {
                return ResourceManager.GetString("countriesid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Country ähnelt.
        /// </summary>
        public static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Country ähnelt.
        /// </summary>
        public static string country_code {
            get {
                return ResourceManager.GetString("country_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Country Name ähnelt.
        /// </summary>
        public static string country_name {
            get {
                return ResourceManager.GetString("country_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create a new account. ähnelt.
        /// </summary>
        public static string create_a_new_account {
            get {
                return ResourceManager.GetString("create_a_new_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create at ähnelt.
        /// </summary>
        public static string create_at {
            get {
                return ResourceManager.GetString("create_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create New ähnelt.
        /// </summary>
        public static string create_new {
            get {
                return ResourceManager.GetString("create_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create date ähnelt.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currency ähnelt.
        /// </summary>
        public static string currency_id {
            get {
                return ResourceManager.GetString("currency_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customer ähnelt.
        /// </summary>
        public static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cust.-no. ähnelt.
        /// </summary>
        public static string customer_no {
            get {
                return ResourceManager.GetString("customer_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cust.-Ref.-No. ähnelt.
        /// </summary>
        public static string customer_reference {
            get {
                return ResourceManager.GetString("customer_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customers ähnelt.
        /// </summary>
        public static string customers {
            get {
                return ResourceManager.GetString("customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date, from ähnelt.
        /// </summary>
        public static string date_from {
            get {
                return ResourceManager.GetString("date_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date, to ähnelt.
        /// </summary>
        public static string date_to {
            get {
                return ResourceManager.GetString("date_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day ähnelt.
        /// </summary>
        public static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete date ähnelt.
        /// </summary>
        public static string delete_date {
            get {
                return ResourceManager.GetString("delete_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delivery date ähnelt.
        /// </summary>
        public static string delivery_date {
            get {
                return ResourceManager.GetString("delivery_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delivery date ähnelt.
        /// </summary>
        public static string delivery_date_report {
            get {
                return ResourceManager.GetString("delivery_date_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delivery term ähnelt.
        /// </summary>
        public static string delivery_term {
            get {
                return ResourceManager.GetString("delivery_term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delivery terms ähnelt.
        /// </summary>
        public static string delivery_terms {
            get {
                return ResourceManager.GetString("delivery_terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Details ähnelt.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Discount, % ähnelt.
        /// </summary>
        public static string discount {
            get {
                return ResourceManager.GetString("discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Discount, % ähnelt.
        /// </summary>
        public static string discount_report {
            get {
                return ResourceManager.GetString("discount_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Due date ähnelt.
        /// </summary>
        public static string due_date {
            get {
                return ResourceManager.GetString("due_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit | Delete ähnelt.
        /// </summary>
        public static string edit_delete {
            get {
                return ResourceManager.GetString("edit_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string edit_h2 {
            get {
                return ResourceManager.GetString("edit_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail ähnelt.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attachment ähnelt.
        /// </summary>
        public static string email_attachment {
            get {
                return ResourceManager.GetString("email_attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Body ähnelt.
        /// </summary>
        public static string email_body {
            get {
                return ResourceManager.GetString("email_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The message [{0}] was canceled. ähnelt.
        /// </summary>
        public static string email_canceled {
            get {
                return ResourceManager.GetString("email_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die From ähnelt.
        /// </summary>
        public static string email_from {
            get {
                return ResourceManager.GetString("email_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occurred sending message [{0}]. {1} ähnelt.
        /// </summary>
        public static string email_message_error {
            get {
                return ResourceManager.GetString("email_message_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail wurde erfolgreich gesendet. ähnelt.
        /// </summary>
        public static string email_message_sent {
            get {
                return ResourceManager.GetString("email_message_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subject ähnelt.
        /// </summary>
        public static string email_subject {
            get {
                return ResourceManager.GetString("email_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To ähnelt.
        /// </summary>
        public static string email_to {
            get {
                return ResourceManager.GetString("email_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter date here ähnelt.
        /// </summary>
        public static string enter_date {
            get {
                return ResourceManager.GetString("enter_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Email field is not a valid e-mail address. ähnelt.
        /// </summary>
        public static string err_email {
            get {
                return ResourceManager.GetString("err_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value for {0} must be between {1} and {2}. ähnelt.
        /// </summary>
        public static string err_range {
            get {
                return ResourceManager.GetString("err_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fax ähnelt.
        /// </summary>
        public static string fax {
            get {
                return ResourceManager.GetString("fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fax ähnelt.
        /// </summary>
        public static string fax_report {
            get {
                return ResourceManager.GetString("fax_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File not exists. ähnelt.
        /// </summary>
        public static string file_not_exists {
            get {
                return ResourceManager.GetString("file_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File path ähnelt.
        /// </summary>
        public static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finance office ähnelt.
        /// </summary>
        public static string finance_office {
            get {
                return ResourceManager.GetString("finance_office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Find by name ähnelt.
        /// </summary>
        public static string find_by_name {
            get {
                return ResourceManager.GetString("find_by_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die German ähnelt.
        /// </summary>
        public static string german {
            get {
                return ResourceManager.GetString("german", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Description ähnelt.
        /// </summary>
        public static string get_descriptions {
            get {
                return ResourceManager.GetString("get_descriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get price ähnelt.
        /// </summary>
        public static string get_prices {
            get {
                return ResourceManager.GetString("get_prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get quantity unit ähnelt.
        /// </summary>
        public static string get_quantity_unit {
            get {
                return ResourceManager.GetString("get_quantity_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get Tax Rate ähnelt.
        /// </summary>
        public static string get_tax_rates {
            get {
                return ResourceManager.GetString("get_tax_rates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        public static string home_site {
            get {
                return ResourceManager.GetString("home_site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IBAN ähnelt.
        /// </summary>
        public static string iban {
            get {
                return ResourceManager.GetString("iban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IBAN ähnelt.
        /// </summary>
        public static string iban_report {
            get {
                return ResourceManager.GetString("iban_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid login attempt ähnelt.
        /// </summary>
        public static string invalid_login_attempt {
            get {
                return ResourceManager.GetString("invalid_login_attempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invoice ähnelt.
        /// </summary>
        public static string invoice {
            get {
                return ResourceManager.GetString("invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invoice-No. ähnelt.
        /// </summary>
        public static string invoice_no {
            get {
                return ResourceManager.GetString("invoice_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invoice not found ähnelt.
        /// </summary>
        public static string invoice_not_found {
            get {
                return ResourceManager.GetString("invoice_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invoices ähnelt.
        /// </summary>
        public static string invoices {
            get {
                return ResourceManager.GetString("invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save? ähnelt.
        /// </summary>
        public static string is_save {
            get {
                return ResourceManager.GetString("is_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last index (invoices) ähnelt.
        /// </summary>
        public static string last_index_invoices {
            get {
                return ResourceManager.GetString("last_index_invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shipping costs ähnelt.
        /// </summary>
        public static string LogisticsServiceChargeDescription {
            get {
                return ResourceManager.GetString("LogisticsServiceChargeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Margin ähnelt.
        /// </summary>
        public static string margin {
            get {
                return ResourceManager.GetString("margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paid / Unpaid ähnelt.
        /// </summary>
        public static string mark_as_paid {
            get {
                return ResourceManager.GetString("mark_as_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The maximum string for {0} length is {1} characters. ähnelt.
        /// </summary>
        public static string max_lenght {
            get {
                return ResourceManager.GetString("max_lenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Methods of payment ähnelt.
        /// </summary>
        public static string method_of_payment {
            get {
                return ResourceManager.GetString("method_of_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mode ähnelt.
        /// </summary>
        public static string mode {
            get {
                return ResourceManager.GetString("mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Month ähnelt.
        /// </summary>
        public static string month {
            get {
                return ResourceManager.GetString("month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;\&quot; {0} \ &quot;must be at least {2} characters long.&quot; ähnelt.
        /// </summary>
        public static string must_be_at_least {
            get {
                return ResourceManager.GetString("must_be_at_least", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Net amount ähnelt.
        /// </summary>
        public static string net_amount {
            get {
                return ResourceManager.GetString("net_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invoice-no. template ähnelt.
        /// </summary>
        public static string no_template_invoices {
            get {
                return ResourceManager.GetString("no_template_invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die e.g. &quot;%P%Y-%N&quot;, %P-Prefix, %Y-Year, %N-Number (&quot;INV16-000101&quot;) ähnelt.
        /// </summary>
        public static string no_template_invoices_info {
            get {
                return ResourceManager.GetString("no_template_invoices_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not paid ähnelt.
        /// </summary>
        public static string not_paid {
            get {
                return ResourceManager.GetString("not_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Optional parameters ähnelt.
        /// </summary>
        public static string optonal_parameters {
            get {
                return ResourceManager.GetString("optonal_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invoice date ähnelt.
        /// </summary>
        public static string order_date {
            get {
                return ResourceManager.GetString("order_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Owner ähnelt.
        /// </summary>
        public static string owner {
            get {
                return ResourceManager.GetString("owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Owner ähnelt.
        /// </summary>
        public static string owner_report {
            get {
                return ResourceManager.GetString("owner_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paid ähnelt.
        /// </summary>
        public static string paid {
            get {
                return ResourceManager.GetString("paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paid at ähnelt.
        /// </summary>
        public static string paid_at {
            get {
                return ResourceManager.GetString("paid_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The password does not match the confirmation password. ähnelt.
        /// </summary>
        public static string password_does_not_match {
            get {
                return ResourceManager.GetString("password_does_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Payment method ähnelt.
        /// </summary>
        public static string payment_method {
            get {
                return ResourceManager.GetString("payment_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Method code ähnelt.
        /// </summary>
        public static string payment_method_code {
            get {
                return ResourceManager.GetString("payment_method_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Payment method ähnelt.
        /// </summary>
        public static string payment_method_name {
            get {
                return ResourceManager.GetString("payment_method_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Payment_method ähnelt.
        /// </summary>
        public static string payment_methodid {
            get {
                return ResourceManager.GetString("payment_methodid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Payment term ähnelt.
        /// </summary>
        public static string payment_term {
            get {
                return ResourceManager.GetString("payment_term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Payment terms ähnelt.
        /// </summary>
        public static string payment_terms {
            get {
                return ResourceManager.GetString("payment_terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % of total sales ähnelt.
        /// </summary>
        public static string percent_of_total_sales {
            get {
                return ResourceManager.GetString("percent_of_total_sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Phone ähnelt.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Phone 2 ähnelt.
        /// </summary>
        public static string phone_2 {
            get {
                return ResourceManager.GetString("phone_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Phone ähnelt.
        /// </summary>
        public static string phone_report {
            get {
                return ResourceManager.GetString("phone_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Picture ähnelt.
        /// </summary>
        public static string picture {
            get {
                return ResourceManager.GetString("picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die plus %1% VAT ähnelt.
        /// </summary>
        public static string plus_vat {
            get {
                return ResourceManager.GetString("plus_vat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Positions ähnelt.
        /// </summary>
        public static string positions {
            get {
                return ResourceManager.GetString("positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pos. ähnelt.
        /// </summary>
        public static string positions_short {
            get {
                return ResourceManager.GetString("positions_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prefix (invoices) ähnelt.
        /// </summary>
        public static string prefix_invoices {
            get {
                return ResourceManager.GetString("prefix_invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Price ähnelt.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Price (netto) ähnelt.
        /// </summary>
        public static string price_netto {
            get {
                return ResourceManager.GetString("price_netto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print ähnelt.
        /// </summary>
        public static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Product ähnelt.
        /// </summary>
        public static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Product costs ähnelt.
        /// </summary>
        public static string product_costs {
            get {
                return ResourceManager.GetString("product_costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quantity ähnelt.
        /// </summary>
        public static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quantity (2) ähnelt.
        /// </summary>
        public static string quantity_2 {
            get {
                return ResourceManager.GetString("quantity_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Quantity 2&quot; column name ähnelt.
        /// </summary>
        public static string quantity_2_column_name {
            get {
                return ResourceManager.GetString("quantity_2_column_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quantity (3) ähnelt.
        /// </summary>
        public static string quantity_3 {
            get {
                return ResourceManager.GetString("quantity_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Quantity 3&quot; column name ähnelt.
        /// </summary>
        public static string quantity_3_column_name {
            get {
                return ResourceManager.GetString("quantity_3_column_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quantity ähnelt.
        /// </summary>
        public static string quantity_report {
            get {
                return ResourceManager.GetString("quantity_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quantity unit ähnelt.
        /// </summary>
        public static string quantity_units {
            get {
                return ResourceManager.GetString("quantity_units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quantity unit ähnelt.
        /// </summary>
        public static string quantity_units_id {
            get {
                return ResourceManager.GetString("quantity_units_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quarter ähnelt.
        /// </summary>
        public static string quarter {
            get {
                return ResourceManager.GetString("quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rates of taxes ähnelt.
        /// </summary>
        public static string rates_of_taxes {
            get {
                return ResourceManager.GetString("rates_of_taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Register ähnelt.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remember this browser? ähnelt.
        /// </summary>
        public static string remember_this_browser {
            get {
                return ResourceManager.GetString("remember_this_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Report parameters ähnelt.
        /// </summary>
        public static string ReportParameters {
            get {
                return ResourceManager.GetString("ReportParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reports ähnelt.
        /// </summary>
        public static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sales ähnelt.
        /// </summary>
        public static string sales {
            get {
                return ResourceManager.GetString("sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sales details ähnelt.
        /// </summary>
        public static string sales_details {
            get {
                return ResourceManager.GetString("sales_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die -- Select Item -- ähnelt.
        /// </summary>
        public static string select_Item {
            get {
                return ResourceManager.GetString("select_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send ähnelt.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send email ähnelt.
        /// </summary>
        public static string send_email {
            get {
                return ResourceManager.GetString("send_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send per EMail ähnelt.
        /// </summary>
        public static string send_per_email {
            get {
                return ResourceManager.GetString("send_per_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set today ähnelt.
        /// </summary>
        public static string set_today {
            get {
                return ResourceManager.GetString("set_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Short mark ähnelt.
        /// </summary>
        public static string shortmark {
            get {
                return ResourceManager.GetString("shortmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show ähnelt.
        /// </summary>
        public static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show report ähnelt.
        /// </summary>
        public static string show_report {
            get {
                return ResourceManager.GetString("show_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Street ähnelt.
        /// </summary>
        public static string street {
            get {
                return ResourceManager.GetString("street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subtotal ähnelt.
        /// </summary>
        public static string subtotal {
            get {
                return ResourceManager.GetString("subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total ähnelt.
        /// </summary>
        public static string sum_price {
            get {
                return ResourceManager.GetString("sum_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tax-No. ähnelt.
        /// </summary>
        public static string tax_number {
            get {
                return ResourceManager.GetString("tax_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tax rate ähnelt.
        /// </summary>
        public static string tax_rate {
            get {
                return ResourceManager.GetString("tax_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text to table ähnelt.
        /// </summary>
        public static string text_to_table {
            get {
                return ResourceManager.GetString("text_to_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text under the table ähnelt.
        /// </summary>
        public static string text_under_the_table {
            get {
                return ResourceManager.GetString("text_under_the_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text under the table (bold) ähnelt.
        /// </summary>
        public static string text_under_the_table_bold {
            get {
                return ResourceManager.GetString("text_under_the_table_bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total amount ähnelt.
        /// </summary>
        public static string total_amount {
            get {
                return ResourceManager.GetString("total_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total sales ähnelt.
        /// </summary>
        public static string total_sales {
            get {
                return ResourceManager.GetString("total_sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total sales by month ähnelt.
        /// </summary>
        public static string total_sales_by_month {
            get {
                return ResourceManager.GetString("total_sales_by_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total sales by quarter ähnelt.
        /// </summary>
        public static string total_sales_by_quarter {
            get {
                return ResourceManager.GetString("total_sales_by_quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total sales by year ähnelt.
        /// </summary>
        public static string total_sales_by_year {
            get {
                return ResourceManager.GetString("total_sales_by_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total value ähnelt.
        /// </summary>
        public static string total_value {
            get {
                return ResourceManager.GetString("total_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Special allowance ähnelt.
        /// </summary>
        public static string TradeAllowanceChargeDescription {
            get {
                return ResourceManager.GetString("TradeAllowanceChargeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We invoice the following services. ähnelt.
        /// </summary>
        public static string TradeLineCommentItem {
            get {
                return ResourceManager.GetString("TradeLineCommentItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unit ähnelt.
        /// </summary>
        public static string unit {
            get {
                return ResourceManager.GetString("unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update at ähnelt.
        /// </summary>
        public static string update_at {
            get {
                return ResourceManager.GetString("update_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upload ähnelt.
        /// </summary>
        public static string upload {
            get {
                return ResourceManager.GetString("upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upload picture ähnelt.
        /// </summary>
        public static string upload_image {
            get {
                return ResourceManager.GetString("upload_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TaxId-No. ähnelt.
        /// </summary>
        public static string ustd_id {
            get {
                return ResourceManager.GetString("ustd_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value ähnelt.
        /// </summary>
        public static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die VAT-No. ähnelt.
        /// </summary>
        public static string vat {
            get {
                return ResourceManager.GetString("vat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Year ähnelt.
        /// </summary>
        public static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ZIP ähnelt.
        /// </summary>
        public static string zip {
            get {
                return ResourceManager.GetString("zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ZUGFeRD ähnelt.
        /// </summary>
        public static string zugferd {
            get {
                return ResourceManager.GetString("zugferd", resourceCulture);
            }
        }
    }
}
