//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mInvoiceAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myinvoiceDBEntities : DbContext
    {
        public myinvoiceDBEntities()
            : base("name=myinvoiceDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Articles> Articles { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Costs> Costs { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Delivery_terms> Delivery_terms { get; set; }
        public virtual DbSet<Invoice_details> Invoice_details { get; set; }
        public virtual DbSet<Invoice_header> Invoice_header { get; set; }
        public virtual DbSet<Payment_method> Payment_method { get; set; }
        public virtual DbSet<Payment_terms> Payment_terms { get; set; }
        public virtual DbSet<Quantity_units> Quantity_units { get; set; }
        public virtual DbSet<Tax_rates> Tax_rates { get; set; }
        public virtual DbSet<Type_of_costs> Type_of_costs { get; set; }
    }
}
