//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mInvoice_api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Articles> Articles { get; set; }
        public DbSet<Clients> Clients { get; set; }
        public DbSet<Countries> Countries { get; set; }
        public DbSet<Currency> Currency { get; set; }
        public DbSet<Customers> Customers { get; set; }
        public DbSet<Delivery_terms> Delivery_terms { get; set; }
        public DbSet<Invoice_details> Invoice_details { get; set; }
        public DbSet<Invoice_header> Invoice_header { get; set; }
        public DbSet<Payment_method> Payment_method { get; set; }
        public DbSet<Payment_terms> Payment_terms { get; set; }
        public DbSet<Quantity_units> Quantity_units { get; set; }
        public DbSet<Tax_rates> Tax_rates { get; set; }
        public DbSet<v_AspNetUsers> v_AspNetUsers { get; set; }
    }
}
